<LabelWidget>:
    Label:
        text: 'a only display glyphs that is available in the font'
        font_size: '15sp'
        color: .9, .2, .1, 1
        text_size: cm(3), mm(20)
        halign: 'right'
        valign: 'middle'
        pos: 400, 380

    Label:
        text: 'can only display glyphs that is available in the font'
        color: .3, .2, .1, 1
        size: self.texture_size
        text_size: cm(3), cm(2)
        pos: 200, 120